library(readxl)
library(tidyr)
library(glue)
library(lubridate)
library(dplyr)

assets <- read_excel('trade.xlsx', sheet='자산정보')
year <- year(today())
days <- seq(ymd(glue("{year}-01-01")), ymd(glue("{year}-12-31")),by='days')

as_list <- crossing(종목코드 = assets$종목코드, 거래일자 = days)
usd1 <- read_excel('trade.xlsx', sheet = '불리오달러')
usd2 <- read_excel('trade.xlsx', sheet = '한투달러')
jpy <- read_excel('trade.xlsx', sheet = '한투엔화')
krw1 <- read_excel('trade.xlsx', sheet = '나무원화')
krw2 <- read_excel('trade.xlsx', sheet = '한투원화')
krw3 <- read_excel('trade.xlsx', sheet = '한투CMA')
krw4 <- read_excel('trade.xlsx', sheet = '한투ISA')
krw5 <- read_excel('trade.xlsx', sheet = '별도원화')
fiw <- read_excel('trade.xlsx', sheet = '외화자산평가') %>%
  select(-외화입출금)